CREATE DATABASE IF NOT EXISTS ophix_test;
CREATE USER IF NOT EXISTS 'ophix_test'@'%' IDENTIFIED BY 'ophixtest123' REQUIRE X509;
GRANT ALL PRIVILEGES ON ophix_test.* TO 'ophix_test'@'%';
FLUSH PRIVILEGES;
