# Generated by Django 5.2.12 on 2026-03-25 06:26

import django.db.models.deletion
import ophix.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ipv4_address', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deployment_ref', models.CharField(blank=True, help_text='Deployment reference (repository name or similar identifier)', max_length=200, null=True)),
                ('venv_name', models.CharField(blank=True, help_text='Name of the Python virtual environment', max_length=100, null=True)),
                ('venv_path', models.CharField(blank=True, help_text='Absolute path to the Python virtual environment', max_length=500, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('api_token', models.CharField(default=ophix.core.models.generate_api_token, max_length=64, unique=True)),
                ('last_token_rotation', models.DateTimeField(blank=True, default=None, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='ophix_core.host')),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('host', 'name'), name='unique_client_per_host')],
            },
        ),
    ]
