# Generated by Django 6.0.6 on 2026-06-06 09:08

import django.db.models.deletion
import django.utils.timezone
import ophix.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('ipv4_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', unique=True, verbose_name='IPv4 address')),
                ('ipv6_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6', unique=True, verbose_name='IPv6 address')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PackageUpdateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=200, unique=True, verbose_name='package name')),
                ('installed_version', models.CharField(max_length=100, verbose_name='installed version')),
                ('latest_version', models.CharField(blank=True, max_length=100, verbose_name='latest version')),
                ('update_available', models.BooleanField(default=False, verbose_name='update available')),
                ('first_recorded_at', models.DateTimeField(auto_now_add=True, help_text='When this package was first seen by check_updates.', verbose_name='first recorded')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='last checked')),
                ('notice', models.TextField(blank=True, help_text='Package release notes read from OPHIX_RELEASE_NOTES.md at last check.', verbose_name='release notes')),
                ('category', models.CharField(blank=True, choices=[('core', 'Core'), ('module', 'Module'), ('addon', 'Add-on'), ('auth', 'Authentication'), ('dbengine', 'Database'), ('theme', 'Theme'), ('language', 'Language')], max_length=20, verbose_name='category')),
                ('sort_order', models.IntegerField(default=999, help_text='Display order within the plugin list. Declared by the package.', verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'Plugin',
                'verbose_name_plural': 'Plugin Versions',
                'ordering': ('sort_order', 'package_name'),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('deployment_ref', models.CharField(blank=True, help_text='Deployment reference (repository name or similar identifier)', max_length=200, null=True, verbose_name='deployment reference')),
                ('venv_name', models.CharField(blank=True, help_text='Name of the Python virtual environment', max_length=100, null=True, verbose_name='virtual environment name')),
                ('venv_path', models.CharField(blank=True, help_text='Absolute path to the Python virtual environment', max_length=500, null=True, verbose_name='virtual environment path')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('api_token', models.CharField(default=ophix.core.models.generate_api_token, max_length=64, unique=True, verbose_name='API token')),
                ('last_token_rotation', models.DateTimeField(blank=True, default=None, null=True, verbose_name='last token rotation')),
                ('rotation_required', models.BooleanField(default=False, verbose_name='rotation required')),
                ('lockout_override', models.BooleanField(default=False, help_text='Set by the token-policy Unlock action. Allows a locked-out client to authenticate once so it can rotate its token. Cleared automatically on successful token rotation.', verbose_name='lockout override')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='ophix_core.host', verbose_name='host')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=10, verbose_name='operation')),
                ('artifact_type', models.CharField(max_length=100, verbose_name='artifact type')),
                ('artifact_name', models.CharField(blank=True, max_length=200, verbose_name='artifact name')),
                ('artifact_id', models.IntegerField(blank=True, null=True, verbose_name='artifact ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='timestamp')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophix_core.client', verbose_name='client')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophix_core.host', verbose_name='host')),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Logs',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('host', 'name'), name='unique_client_per_host'),
        ),
    ]
