# Generated by Django 6.0.4 on 2026-05-01 10:39

import django.db.models.deletion
import django.utils.timezone
import ophix.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophix_core', '0002_access_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslog',
            options={'ordering': ('-timestamp',), 'verbose_name': 'Access Log', 'verbose_name_plural': 'Access Logs'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('name',), 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ('name',), 'verbose_name': 'Host', 'verbose_name_plural': 'Hosts'},
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='artifact_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='artifact ID'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='artifact_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='artifact name'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='artifact_type',
            field=models.CharField(max_length=100, verbose_name='artifact type'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophix_core.client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ophix_core.host', verbose_name='host'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='operation',
            field=models.CharField(max_length=10, verbose_name='operation'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='client',
            name='api_token',
            field=models.CharField(default=ophix.core.models.generate_api_token, max_length=64, unique=True, verbose_name='API token'),
        ),
        migrations.AlterField(
            model_name='client',
            name='deployment_ref',
            field=models.CharField(blank=True, help_text='Deployment reference (repository name or similar identifier)', max_length=200, null=True, verbose_name='deployment reference'),
        ),
        migrations.AlterField(
            model_name='client',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='client',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='ophix_core.host', verbose_name='host'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_token_rotation',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='last token rotation'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='venv_name',
            field=models.CharField(blank=True, help_text='Name of the Python virtual environment', max_length=100, null=True, verbose_name='virtual environment name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='venv_path',
            field=models.CharField(blank=True, help_text='Absolute path to the Python virtual environment', max_length=500, null=True, verbose_name='virtual environment path'),
        ),
        migrations.AlterField(
            model_name='host',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='host',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ipv4_address',
            field=models.GenericIPAddressField(protocol='IPv4', unique=True, verbose_name='IPv4 address'),
        ),
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
    ]
