"""
ophix-manage create_backup_script
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Generate ophix-backup.sh — a scheduled backup script that exports all server
data to dated JSON files.

The generated script:
  - Lives alongside .env in the directory where this command is run
  - Sources .env at runtime so BACKUP_PATH and BACKUP_PASSPHRASE are read
    from the same place as all other server config
  - Auto-detects which domain exports are available on this server
  - Uses a passphrase for exports that support encryption (when BACKUP_PASSPHRASE
    is set in .env); runs without encryption if the variable is absent or blank
  - Bakes in the ophix-manage path from the running venv so no PATH or
    VENV_NAME configuration is needed

Re-run this command after upgrading or moving the venv to refresh the baked-in
manage path.

Usage::

    ophix-manage create_backup_script
    ophix-manage create_backup_script --output-file /home/websites/credserver/ophix-backup.sh
"""

import os
import stat
import sys
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError


_BACKUP_SCRIPT_TEMPLATE = """\
#!/usr/bin/env bash
# ophix-backup.sh — {{ server_name }}
# Generated by: ophix-manage create_backup_script
#
# Re-generate at any time to pick up venv path changes:
#   ophix-manage create_backup_script
#
# Required .env entries (file co-located with this script):
#   BACKUP_PATH=/path/to/backup/directory
#   BACKUP_PASSPHRASE=your-passphrase   # omit to export without encryption
#
# Suggested cron entry (daily at 02:00):
#   0 2 * * * {{ script_path }} >> /var/log/ophix-backup.log 2>&1

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

if [[ ! -f "$ENV_FILE" ]]; then
    echo "Error: .env not found at $ENV_FILE" >&2
    exit 1
fi

# Load .env so management commands see all vars via os.environ
set -a
# shellcheck source=/dev/null
source "$ENV_FILE"
set +a

if [[ -z "${BACKUP_PATH:-}" ]]; then
    echo "Error: BACKUP_PATH is not set in $ENV_FILE" >&2
    exit 1
fi

MANAGE="{{ manage_path }}"
DATE="$(date +%Y%m%d_%H%M%S)"

mkdir -p "$BACKUP_PATH"

# Returns 0 if the management command is available on this server
has_cmd() { "$MANAGE" "$1" --help > /dev/null 2>&1; }

# Populate passphrase args when BACKUP_PASSPHRASE is set; empty array otherwise
pass_args=()
if [[ -n "${BACKUP_PASSPHRASE:-}" ]]; then
    pass_args=(--passphrase-env BACKUP_PASSPHRASE)
fi

echo "[$DATE] Starting backup — {{ server_name }}"

# ── Plain exports (no passphrase) ─────────────────────────────────────────────
for cmd in export_hosts export_settings export_tasks export_zones; do
    if has_cmd "$cmd"; then
        "$MANAGE" "$cmd" --output-file "$BACKUP_PATH/${cmd#export_}_${DATE}.json" --quiet
        echo "  ${cmd#export_}.json written"
    fi
done

# ── Encrypted exports (passphrase optional) ───────────────────────────────────
for cmd in export_clients export_confs export_creds export_certs export_dns_servers; do
    if has_cmd "$cmd"; then
        "$MANAGE" "$cmd" \\
            --output-file "$BACKUP_PATH/${cmd#export_}_${DATE}.json" \\
            "${pass_args[@]}" --quiet
        echo "  ${cmd#export_}.json written"
    fi
done

echo "[$DATE] Backup complete — $BACKUP_PATH"
"""


def _render(template: str, ctx: dict) -> str:
    from jinja2 import Environment, StrictUndefined
    env = Environment(undefined=StrictUndefined, keep_trailing_newline=True)
    return env.from_string(template).render(**ctx)


class Command(BaseCommand):
    help = "Generate ophix-backup.sh for scheduled server backups."

    def add_arguments(self, parser):
        parser.add_argument(
            "--output-file",
            metavar="PATH",
            help=(
                "Where to write the script. "
                "Default: ophix-backup.sh in the current directory."
            ),
        )
        parser.add_argument(
            "--quiet",
            action="store_true",
            help="Suppress output.",
        )

    def handle(self, *args, **options):
        quiet = options["quiet"]

        manage_path = Path(sys.executable).parent / "ophix-manage"
        if not manage_path.exists():
            raise CommandError(
                f"ophix-manage not found at {manage_path}. "
                "Run this command from the server venv."
            )

        server_name = getattr(settings, "SERVER_NAME", "ophix")

        output_file = options.get("output_file")
        if output_file:
            script_path = Path(output_file).resolve()
        else:
            script_path = Path.cwd() / "ophix-backup.sh"

        ctx = {
            "manage_path": str(manage_path),
            "server_name": server_name,
            "script_path": str(script_path),
        }

        content = _render(_BACKUP_SCRIPT_TEMPLATE, ctx)

        script_path.write_text(content, encoding="utf-8")
        script_path.chmod(stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP)

        if not quiet:
            self.stdout.write(self.style.SUCCESS(f"Generated: {script_path}"))
            self.stdout.write("")

            env_file = script_path.parent / ".env"
            missing = []
            if env_file.exists():
                env_text = env_file.read_text(encoding="utf-8")
                if "BACKUP_PATH" not in env_text:
                    missing.append("BACKUP_PATH=/path/to/backup/directory")
                if "BACKUP_PASSPHRASE" not in env_text:
                    missing.append("BACKUP_PASSPHRASE=your-passphrase")
            else:
                missing = [
                    "BACKUP_PATH=/path/to/backup/directory",
                    "BACKUP_PASSPHRASE=your-passphrase",
                ]

            if missing:
                self.stdout.write("Add to .env:")
                for line in missing:
                    self.stdout.write(f"  {line}")
                self.stdout.write("")

            self.stdout.write("Suggested cron entry (daily at 02:00):")
            self.stdout.write(f"  0 2 * * * {script_path} >> /var/log/ophix-backup.log 2>&1")
