"""
ophix.core.management.commands.run_install
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Complete the installation using settings from .<server_name>.conf.

Must be run after configure_install. Performs all non-root steps and
generates a sudo script for the steps that require root.

Steps performed directly:
  - Creates INSTALL_DIR directory structure
  - Copies TLS certificate, key, and optional CA bundle into place
  - Generates <server_name>.nginx.conf
  - Generates <server_name>.service (systemd)
  - Generates <server_name>_sudo_install.sh
  - Generates <server_name>_sudo_uninstall.sh
  - Runs: migrate
  - Runs: collectstatic --noinput
  - Creates or updates the superuser
  - Activates theme (if configured)
  - Sets admin title and header on the active theme
  - Loads documentation for all installed apps (if ophix-docs is installed)

After this command succeeds, run:
    sudo bash <server_name>_sudo_install.sh

Usage::

    ophix-manage run_install credserver
    ophix-manage run_install confserver
"""

import configparser
import os
import shutil
import sys
from pathlib import Path

from django.core.management import call_command
from django.core.management.base import BaseCommand, CommandError

from ophix.core.management.commands.generate_deploy_config import (
    _discover_domain_version,
    _render_template,
    _slugify,
)


# Subdirectories to create under INSTALL_DIR.
# (relative path, octal mode)
_SUBDIRS = [
    ("logs",        0o2770),
    ("media",       0o2770),
    ("run",         0o2755),
    ("ssl",         0o750),
    ("ssl/certs",   0o750),
    ("ssl/private", 0o700),
    ("static",      0o755),
]


# ---------------------------------------------------------------------------
# Plugin hook discovery
# ---------------------------------------------------------------------------

def _call_plugin_run_hooks(conf, command):
    """
    Call install_run(conf, command) on each installed ophix plugin that
    exposes it. Called before migrate so plugins can write encryption keys
    and other required settings to .env before database setup runs.
    """
    import importlib
    try:
        from importlib.metadata import entry_points
        eps = entry_points(group="ophix.plugins")
    except Exception:
        return

    for ep in eps:
        try:
            mod = importlib.import_module(ep.value)
        except Exception:
            continue
        hook = getattr(mod, "install_run", None)
        if callable(hook):
            command.stdout.write(f"  [{ep.name}]\n")
            try:
                hook(conf, command)
            except Exception as exc:
                command.stdout.write(
                    command.style.WARNING(f"  Plugin hook error ({ep.name}): {exc}\n")
                )


# ---------------------------------------------------------------------------
# Jinja2 template for sudo_install.sh
# ---------------------------------------------------------------------------

_SUDO_INSTALL_TEMPLATE = """\
#!/usr/bin/env bash
# {{ server_name }} — sudo install script
# Generated by: ophix-manage run_install {{ server_name }}
#
# Run as root after ophix-manage run_install completes:
#   sudo bash {{ server_name }}_sudo_install.sh

set -e

SERVICE_USER="{{ service_user }}"
SERVICE_GROUP="{{ service_group }}"
NGINX_GROUP="{{ nginx_group }}"
INSTALL_DIR="{{ install_dir }}"
SLUG="{{ slug }}"

echo "=== Setting ownership ==="
chown -R "$SERVICE_USER:$SERVICE_GROUP" "$INSTALL_DIR"

# Parent directory needs world-execute so nginx can traverse into the install dir.
# Home directories are 750 by default — this adds traverse-only, not read access.
chmod o+x "$(dirname "$INSTALL_DIR")"

# logs/ and run/ need nginx group read access
for dir in logs media run; do
    chown "$SERVICE_USER:$NGINX_GROUP" "$INSTALL_DIR/$dir"
    chmod 2770 "$INSTALL_DIR/$dir"
done

# run/ socket dir — nginx must traverse it
chown "$SERVICE_USER:$NGINX_GROUP" "$INSTALL_DIR/run"
chmod 2755 "$INSTALL_DIR/run"

# ssl/ — private keys must NOT be readable by nginx
chown -R "$SERVICE_USER:$SERVICE_GROUP" "$INSTALL_DIR/ssl"
chmod 750 "$INSTALL_DIR/ssl"
chmod 750 "$INSTALL_DIR/ssl/certs"
chmod 700 "$INSTALL_DIR/ssl/private"

if [ -f "$INSTALL_DIR/ssl/certs/$SLUG.crt" ]; then
    chmod 644 "$INSTALL_DIR/ssl/certs/$SLUG.crt"
fi
{% if ca_bundle_dest %}
if [ -f "{{ ca_bundle_dest }}" ]; then
    chmod 644 "{{ ca_bundle_dest }}"
fi
{% endif %}
if [ -f "$INSTALL_DIR/ssl/private/$SLUG.key" ]; then
    chmod 640 "$INSTALL_DIR/ssl/private/$SLUG.key"
fi

echo "=== Installing nginx configuration ==="
cp "$INSTALL_DIR/{{ slug }}.nginx.conf" /etc/nginx/sites-available/$SLUG.conf
ln -sf /etc/nginx/sites-available/$SLUG.conf /etc/nginx/sites-enabled/
nginx -t
systemctl reload nginx

echo "=== Installing systemd service ==="
cp "$INSTALL_DIR/{{ slug }}.service" /etc/systemd/system/
systemctl daemon-reload
systemctl enable "$SLUG"
systemctl start "$SLUG"

echo ""
echo "Installation complete. Check service status:"
echo "  sudo systemctl status $SLUG"
echo "  sudo journalctl -u $SLUG -f"
"""


_SUDO_UNINSTALL_TEMPLATE = """\
#!/usr/bin/env bash
# {{ server_name }} — sudo uninstall script
# Generated by: ophix-manage run_install {{ server_name }}
#
# Run as root to remove system-level configuration.
# This script does NOT remove the install directory or its data.

set -e

SLUG="{{ slug }}"

echo "=== Stopping and disabling service ==="
systemctl stop "$SLUG" || true
systemctl disable "$SLUG" || true
rm -f /etc/systemd/system/$SLUG.service
systemctl daemon-reload

echo "=== Removing nginx configuration ==="
rm -f /etc/nginx/sites-enabled/$SLUG.conf
rm -f /etc/nginx/sites-available/$SLUG.conf
nginx -t && systemctl reload nginx || true

echo ""
echo "Service and nginx config removed."
echo "The install directory has NOT been removed. To remove it:"
echo "  sudo rm -rf {{ install_dir }}"
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _read_conf(conf_path: Path) -> configparser.ConfigParser:
    conf = configparser.ConfigParser()
    conf.read(str(conf_path))
    return conf


def _ensure_dir(path: Path, mode: int, stdout, style):
    created = False
    if not path.exists():
        try:
            path.mkdir(parents=True, exist_ok=True)
            created = True
        except PermissionError:
            stdout.write(
                style.ERROR(f"  FAILED (permission): {path}\n")
                + f"  The sudo script will handle this directory.\n"
            )
            return
    try:
        path.chmod(mode)
    except PermissionError:
        pass
    label = "Created" if created else "Exists "
    stdout.write(style.SUCCESS(f"  {label}: {path}\n"))


def _render_inline(template_str: str, ctx: dict) -> str:
    from jinja2 import Environment, StrictUndefined
    env = Environment(undefined=StrictUndefined, keep_trailing_newline=True)
    return env.from_string(template_str).render(**ctx)


def _copy_tls(src: str, dest: Path, stdout, style, label: str):
    if not src:
        return
    src_path = Path(src)
    if not src_path.exists():
        stdout.write(style.WARNING(f"  Warning: {label} source not found: {src}\n"))
        return
    shutil.copy2(str(src_path), str(dest))
    stdout.write(style.SUCCESS(f"  Copied {label}: {src_path.name} → {dest}\n"))


def _activate_theme(theme_name: str, stdout, style):
    if not theme_name:
        return
    try:
        call_command("set_theme", theme_name, verbosity=0)
        stdout.write(style.SUCCESS(f"  Theme activated: {theme_name}\n"))
    except Exception as exc:
        stdout.write(style.WARNING(f"  Could not activate theme '{theme_name}': {exc}\n"))


def _set_admin_labels(title: str, header: str, stdout, style):
    if not title and not header:
        return
    try:
        from admin_interface.models import Theme
        active = Theme.objects.filter(active=True).first()
        if active:
            if title:
                active.title = title
            if header:
                active.name = header
            active.save()
            stdout.write(style.SUCCESS(f"  Admin title set: {title!r}\n"))
        else:
            stdout.write(style.WARNING("  No active theme found — admin title not set.\n"))
    except Exception as exc:
        stdout.write(style.WARNING(f"  Could not set admin title: {exc}\n"))


def _auto_install_docs(stdout, style):
    """Load docs for all installed apps that ship them, if ophix-docs is installed."""
    try:
        from django.apps import apps as django_apps
        if not django_apps.is_installed("ophix_docs"):
            return
        from pathlib import Path as _Path
        found = []
        for app_config in django_apps.get_app_configs():
            docs_path = _Path(app_config.path) / "docs"
            if (docs_path.is_dir()
                    and list(docs_path.glob("*.md"))
                    and (docs_path / "sections.yaml").is_file()):
                found.append(app_config.name)
        if not found:
            stdout.write(style.WARNING("  ophix-docs installed but no app docs found.\n"))
            return
        app_list = ",".join(found)
        stdout.write(f"  Found docs in: {app_list}\n")
        call_command("ophix_docs_update", include_app_docs=app_list, verbosity=0)
        stdout.write(style.SUCCESS("  Documentation loaded.\n"))
    except Exception as exc:
        stdout.write(style.WARNING(f"  Could not auto-load docs: {exc}\n"))


def _create_or_update_superuser(username: str, email: str, password: str, stdout, style):
    from django.contrib.auth import get_user_model
    User = get_user_model()
    if User.objects.filter(username=username).exists():
        user = User.objects.get(username=username)
        user.set_password(password)
        user.is_staff = True
        user.is_superuser = True
        if email:
            user.email = email
        user.save()
        stdout.write(style.SUCCESS(f"  Superuser updated: {username}\n"))
    else:
        User.objects.create_superuser(username=username, email=email or "", password=password)
        stdout.write(style.SUCCESS(f"  Superuser created: {username}\n"))


# ---------------------------------------------------------------------------
# Command
# ---------------------------------------------------------------------------

class Command(BaseCommand):
    help = (
        "Complete the installation using .<server_name>.conf. "
        "Run after configure_install."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "server_name",
            help="Server slug matching the name used in configure_install",
        )
        parser.add_argument(
            "--nginx-group", metavar="GROUP", default="www-data",
            help="System group for the nginx process (default: www-data)",
        )
        parser.add_argument(
            "--skip-migrate", action="store_true",
            help="Skip the database migration step",
        )
        parser.add_argument(
            "--skip-collectstatic", action="store_true",
            help="Skip collectstatic",
        )
        parser.add_argument(
            "--skip-superuser", action="store_true",
            help="Skip superuser creation/update",
        )

    def handle(self, *args, **options):
        server_name = options["server_name"].lower().strip()
        conf_path = Path.cwd() / f".{server_name}.conf"

        if not conf_path.exists():
            raise CommandError(
                f"Configuration file not found: {conf_path}\n"
                f"Run: ophix-manage configure_install {server_name}"
            )

        conf = _read_conf(conf_path)

        def _get(section, key, fallback=""):
            return conf.get(section, key, fallback=fallback)

        install_dir   = Path(_get("server", "install_dir") or str(Path.cwd()))
        hostname      = _get("server", "hostname")
        service_user  = _get("server", "service_user", "ophix")
        service_group = _get("server", "service_group", service_user)

        cert_src      = _get("tls", "cert_path")
        key_src       = _get("tls", "key_path")
        ca_bundle_src = _get("tls", "ca_bundle")

        db_engine   = _get("database", "engine", "mariadb")
        db_host     = _get("database", "host", "localhost")
        db_port     = _get("database", "port", "3306")

        su_username = _get("superuser", "username", "admin")
        su_email    = _get("superuser", "email", "")
        su_password = _get("superuser", "password", "")

        activate_theme  = _get("admin", "activate_theme", "")
        admin_title     = _get("admin", "admin_title", "")
        admin_header    = _get("admin", "admin_header", "")
        http_redirect   = conf.getboolean("server", "http_redirect", fallback=True)

        slug = _slugify(server_name)
        nginx_group = options["nginx_group"]

        dist_name, domain_ver = _discover_domain_version()

        self.stdout.write(f"\nInstalling {server_name}...\n")
        self.stdout.write("=" * 60 + "\n\n")

        # ------------------------------------------------------------------ #
        # 1. Create directory structure
        # ------------------------------------------------------------------ #
        self.stdout.write(f"Creating directory structure in {install_dir}\n")
        _ensure_dir(install_dir, 0o755, self.stdout, self.style)
        for rel, mode in _SUBDIRS:
            _ensure_dir(install_dir / rel, mode, self.stdout, self.style)
        self.stdout.write("\n")

        # ------------------------------------------------------------------ #
        # 2. Copy TLS files
        # ------------------------------------------------------------------ #
        self.stdout.write("Copying TLS files\n")
        cert_dest = install_dir / "ssl" / "certs" / f"{slug}.crt"
        key_dest  = install_dir / "ssl" / "private" / f"{slug}.key"
        _copy_tls(cert_src, cert_dest, self.stdout, self.style, "certificate")
        _copy_tls(key_src,  key_dest,  self.stdout, self.style, "private key")

        ca_bundle_dest = ""
        if ca_bundle_src:
            ca_name = Path(ca_bundle_src).name
            ca_dest = install_dir / "ssl" / "certs" / ca_name
            _copy_tls(ca_bundle_src, ca_dest, self.stdout, self.style, "CA bundle")
            ca_bundle_dest = str(ca_dest)

        self.stdout.write("\n")

        # ------------------------------------------------------------------ #
        # 3. Generate nginx config
        # ------------------------------------------------------------------ #
        self.stdout.write("Generating nginx config\n")
        ctx = {
            "portal_name":     slug,
            "server_hostname": hostname,
            "install_dir":     str(install_dir),
            "server_name":     server_name,
            "static_root":     str(install_dir / "static"),
            "media_root":      str(install_dir / "media"),
            "venv_path":       sys.prefix,
            "domain_version":  domain_ver or "",
            "http_redirect":   http_redirect,
        }
        if ca_bundle_dest:
            ctx["ca_bundle_dest"] = ca_bundle_dest

        nginx_content = _render_template("nginx.conf.j2", ctx)
        if ca_bundle_dest:
            # Append ssl_trusted_certificate directive to the HTTPS block
            ssl_line = f"    ssl_trusted_certificate {ca_bundle_dest};\n"
            nginx_content = nginx_content.replace(
                "    ssl_prefer_server_ciphers on;\n",
                f"    ssl_prefer_server_ciphers on;\n{ssl_line}",
                1,
            )
        nginx_path = install_dir / f"{slug}.nginx.conf"
        nginx_path.write_text(nginx_content, encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(f"  Written: {nginx_path}\n\n"))

        # ------------------------------------------------------------------ #
        # 4. Generate systemd service
        # ------------------------------------------------------------------ #
        self.stdout.write("Generating systemd service\n")
        svc_ctx = {
            **ctx,
            "description":   server_name,
            "service_user":  service_user,
            "service_group": service_group,
        }
        svc_content = _render_template("gunicorn.service.j2", svc_ctx)
        svc_path = install_dir / f"{slug}.service"
        svc_path.write_text(svc_content, encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(f"  Written: {svc_path}\n\n"))

        # ------------------------------------------------------------------ #
        # 5. Generate sudo scripts
        # ------------------------------------------------------------------ #
        self.stdout.write("Generating sudo scripts\n")
        sudo_ctx = {
            "server_name":   server_name,
            "slug":          slug,
            "install_dir":   str(install_dir),
            "service_user":  service_user,
            "service_group": service_group,
            "nginx_group":   nginx_group,
            "ca_bundle_dest": ca_bundle_dest,
        }
        install_sh = install_dir / f"{slug}_sudo_install.sh"
        install_sh.write_text(
            _render_inline(_SUDO_INSTALL_TEMPLATE, sudo_ctx), encoding="utf-8"
        )
        try:
            install_sh.chmod(0o755)
        except OSError:
            pass
        self.stdout.write(self.style.SUCCESS(f"  Written: {install_sh}\n"))

        uninstall_sh = install_dir / f"{slug}_sudo_uninstall.sh"
        uninstall_sh.write_text(
            _render_inline(_SUDO_UNINSTALL_TEMPLATE, sudo_ctx), encoding="utf-8"
        )
        try:
            uninstall_sh.chmod(0o755)
        except OSError:
            pass
        self.stdout.write(self.style.SUCCESS(f"  Written: {uninstall_sh}\n\n"))

        # ------------------------------------------------------------------ #
        # 6. Plugin install hooks (run before migrate — keys must be in .env first)
        # ------------------------------------------------------------------ #
        self.stdout.write("Plugin setup\n")
        _call_plugin_run_hooks(conf, self)

        # Reload .env so that any keys written by plugin hooks (e.g.
        # CRED_ENCRYPTION_KEY) are visible to the migrate step.  set_key()
        # writes to disk but does not update os.environ in the running process.
        try:
            from dotenv import find_dotenv, load_dotenv
            _env_file = find_dotenv(usecwd=True)
            if _env_file:
                load_dotenv(_env_file, override=True)
        except Exception:
            pass

        self.stdout.write("\n")

        # ------------------------------------------------------------------ #
        # 7. migrate
        # ------------------------------------------------------------------ #
        if not options["skip_migrate"]:
            self.stdout.write("Running migrate\n")
            try:
                call_command("migrate", verbosity=1)
            except Exception as exc:
                raise CommandError(f"migrate failed: {exc}")
            self.stdout.write("\n")

        # ------------------------------------------------------------------ #
        # 8. collectstatic
        # ------------------------------------------------------------------ #
        if not options["skip_collectstatic"]:
            self.stdout.write("Running collectstatic\n")
            try:
                call_command("collectstatic", interactive=False, verbosity=1)
            except Exception as exc:
                self.stdout.write(self.style.WARNING(f"  collectstatic warning: {exc}\n"))
            self.stdout.write("\n")

        # ------------------------------------------------------------------ #
        # 9. Create / update superuser
        # ------------------------------------------------------------------ #
        if not options["skip_superuser"]:
            self.stdout.write("Creating superuser\n")
            if su_password:
                _create_or_update_superuser(
                    su_username, su_email, su_password, self.stdout, self.style
                )
            else:
                self.stdout.write(
                    self.style.WARNING(
                        "  No superuser password in config — skipping.\n"
                        "  Run: ophix-manage createsuperuser\n"
                    )
                )
            self.stdout.write("\n")

        # ------------------------------------------------------------------ #
        # 10. Activate theme + set admin labels
        # ------------------------------------------------------------------ #
        if activate_theme or admin_title:
            self.stdout.write("Configuring admin UI\n")
            if activate_theme:
                _activate_theme(activate_theme, self.stdout, self.style)
            if admin_title or admin_header:
                _set_admin_labels(admin_title, admin_header, self.stdout, self.style)
            self.stdout.write("\n")

        # ------------------------------------------------------------------ #
        # 11. Load documentation
        # ------------------------------------------------------------------ #
        self.stdout.write("Loading documentation\n")
        _auto_install_docs(self.stdout, self.style)
        self.stdout.write("\n")

        # ------------------------------------------------------------------ #
        # Summary
        # ------------------------------------------------------------------ #
        self.stdout.write(self.style.SUCCESS("=" * 60 + "\n"))
        self.stdout.write(self.style.SUCCESS("Installation complete.\n\n"))
        self.stdout.write("Final step — run as root:\n\n")
        self.stdout.write(f"  sudo bash {install_sh}\n\n")
        self.stdout.write(
            f"Then browse to: https://{hostname}/admin/\n"
            f"Login: {su_username} / <your password>\n"
        )
